---
- name: Run show clock commands
  hosts: cisco
  gather_facts: false
  connection: local

  tasks:
    - name: RUN 'SHOW VERSION'
      ios_command:
        host: "cisco"
        username: "root"
        password: "1178710"
        commands:
          - show version
